### ISSUE TITLE
Toggles not working in Zoom 5.3.1

### ISSUE THREAD

**Issue by ianbsound** [smitmartijn/streamdeck-zoom-plugin#10]
I updated Zoom to 5.3.1 and this has stopped the Mic mute, Video mute and Share screen buttons from working.  I haven't tested your other functions, sorry.
Manually pressing the keyboard hotkeys still work gloablly, but I get a yellow error triangle and nothing happens if I try and use the Streamdeck toggle buttons.

**Comment by statik** [comment]
@ianbsound are you seeing this on windows or macOS? can you attach streamdeck logs? https://developer.elgato.com/documentation/stream-deck/sdk/create-your-own-plugin/#logging has info on where to find the logs.

**Comment by ianbsound** [comment]
@statik weirdly I opened Zoom to double check and to see if I could generate logs with the error for today, and the toggles are working. They're reading the status within Zoom too.
Really sorry, I must have been doing somthing wrong at my end!  Thanks for the reply though.
