### ISSUE TITLE
Windows Release

### ISSUE THREAD

**Issue by oldjohngalt** [smitmartijn/streamdeck-zoom-plugin#12]
@smitmartijn Would it be possible to add the windows release or any guidance on how to compile your recent changes?

**Comment by smitmartijn** [comment]
The docs need updating, yes..I'll get around to it soon. In the meantime, it's relatively simple; run `cmake .` from the MSVC cmd prompt and it'll generate a Visual Studio solution for you. Then compiling can be done from VS.
