### ISSUE TITLE
Green warning sign on every action

### ISSUE THREAD

**Issue by ybizeul** [smitmartijn/streamdeck-zoom-plugin#13]
Mute / Camera buttons are gray and when I press it, it displays a green warning sign for a few seconds.

```
08:47:08.7313          void ESDActionsGridViewModel::onKeyPressed(): Key 6 pressed: com.lostdomain.zoom.mutetoggle
08:47:08.8330          void ESDActionsGridViewModel::onKeyReleased(): Key 6 released: com.lostdomain.zoom.mutetoggle
08:47:13.9295          void ESDActionsGridViewModel::onKeyPressed(): Key 6 pressed: com.lostdomain.zoom.mutetoggle
08:47:14.0803          void ESDActionsGridViewModel::onKeyReleased(): Key 6 released: com.lostdomain.zoom.mutetoggle
```

I didn't see any other meaningful logs.

**Comment by ybizeul** [comment]
```
default	19:45:56.460155+0100	sdzoomplugin	ZoomStreamDeckPlugin.cpp: stored handle
default	19:45:56.505656+0100	sdzoomplugin	ZoomStreamDeckPlugin.cpp: stored handle
default	19:46:01.469918+0100	sdzoomplugin	ESDConnectionManager.cpp: Failed with reason: The opening handshake timed out
default	19:46:01.513086+0100	sdzoomplugin	ESDConnectionManager.cpp: Failed with reason: The opening handshake timed out
```

**Comment by smitmartijn** [comment]
Hi,

This is a StreamDeck software issue, where it's not running entirely correctly and the plugins can't be contacted. I'd recommend restarting it, or reinstalling it.

**Comment by ybizeul** [comment]
Other plugins are working just fine.

I figured there was two instances installed with different IDs

```
com.lostdomain.zoom.sdPlugin/
com.lostdomain.zoom.streamdeckplugin.sdPlugin/
```

Removed both, reinstalled the one from git, and it's working, but extremely slow so not very useful, I'll use keyboard shortcuts in the end

Thanks

**Comment by smitmartijn** [comment]
It sounds like you're not using the plugin from the StreamDeck Store - please do so. The ones I posted separately for download, are not that efficient.

**Comment by ybizeul** [comment]
A bit better indeed. Thanks
