### ISSUE TITLE
Feature Request: Mute / unmute instead of toggle

### ISSUE THREAD

**Issue by etoykan** [smitmartijn/streamdeck-zoom-plugin#18]
I want to be able to mute and turn my cam off with a single click (let's say someone at the door and you just want to turn everything off). I could do it with multi actions if there was the ability to only mute and to turn the cam off instead of toggling.

**Comment by smitmartijn** [comment]
This is now possible in v3.0 (soon to be in the StreamDeck Store) by adding a custom shortcut button and configuring it to run "command+I" - please update to v3.0 (when it's available, usually only takes a day or so for them to publish it) and try it. Re-open issue if it's not working.
