### ISSUE TITLE
Feature Request: Show chat

### ISSUE THREAD

**Issue by etoykan** [smitmartijn/streamdeck-zoom-plugin#19]
It's hard to find the show chat button specifically when I'm sharing my screen so it would be great to have this functionality.

**Comment by smitmartijn** [comment]
This is now possible in v3.0 (soon to be in the StreamDeck Store) by adding a custom shortcut button and configuring it to run "shift+command+H" - please update to v3.0 (when it's available, usually only takes a day or so for them to publish it) and try it. Re-open issue if it's not working.
