### ISSUE TITLE
Feature Request: Show invite dialog

### ISSUE THREAD

**Issue by etoykan** [smitmartijn/streamdeck-zoom-plugin#20]
Zoom people manage to hide the "invite" button very well 👏  specifically when you are sharing your screen. So it would be great to ho have this functionality.

**Comment by smitmartijn** [comment]
This is now possible in v3.0 (soon to be in the StreamDeck Store) by adding a custom shortcut button and configuring it to run "command+I" - please update to v3.0 (when it's available, usually only takes a day or so for them to publish it) and try it. Re-open issue if it's not working.
