### ISSUE TITLE
Add support for languages other than English

### ISSUE THREAD

**Issue by Timac** [smitmartijn/streamdeck-zoom-plugin#21]
**Steps to Reproduce:**

- Set macOS Big Sur to run in French or German
- Launch Zoom in French or German
- Launch Stream Deck
- Try to mute/unmute Zoom

Result: Mute/unmute fails when not running in English.
Expected Result: It would be nice to add support for languages other than English (French, German, Spanish, …) 

Example of change required:
You would need to change `Unmute Audio` to `Audiostummschaltung aufheben` in `osToogleZoomMute()` in order to have mute/unmute working in German.

**Comment by smitmartijn** [comment]
That is an extremely good point, I have not thought about that before. I'm gearing up to make the key shortcuts (for Windows) configurable, maybe it should go back to using shortcuts on macOS as well. That would eliminate that problem, otherwise, all languages have to be taken into account.

**Comment by agnf** [comment]
you don't have to set MacOS to a different language, instead you can set Zoom to another language. To do so, Option-Click on the Zoom icon in your Dock and choose another language.

This is also a workaround for those not working with an English MacOS: set your Zoom to English and the plugin will work.

**Comment by smitmartijn** [comment]
Version 3.0 (coming your way @Timac, to put on the StreamDeck Store) will fix this, by allowing you to input the text of the menu that the plugin is clicking. Tested with German, but it'll work with anything.
