### ISSUE TITLE
Lag between button press and Zoom action

### ISSUE THREAD

**Issue by idealerror** [smitmartijn/streamdeck-zoom-plugin#27]
Hello,

On MacOS and I believe happens on Windows as well, there is a few second lag between when a button is clicked (example Toggle Mute/Unmute).  This lag does not happen when pressing the keyboard shortcut (cmd+shift+a on Mac). Is this a bug or a feature?

**Comment by smitmartijn** [comment]
The plugin only polls the Zoom client every few seconds, so yes, there is an expected delay between pressing the button and seeing the result.
