### ISSUE TITLE
Windows alert sound on mute/unmute

### ISSUE THREAD

**Issue by vanclute** [smitmartijn/streamdeck-zoom-plugin#29]
Every time I press the mute/unmute button on my stream deck while in a Zoom, I get a standard Windows alert sound triggering.  I don't know why and can't figure out how to stop it.  Is there a way to turn that off?

**Comment by smitmartijn** [comment]
Hi,

Does the action actually work? Usually a [thump] sound is the result of the key shortcut not working. If it's not working, either change the mute toggle shortcut back to Zoom's default, or stop using the button. ;-)

**Comment by vanclute** [comment]
It does work, and it's not a thumb sound, it's the standard Windows "chime bells" or whatever... The mute does work, it just also plays a sound for some reason.  It's the only button that does, all others simply trigger what they should trigger.

**Comment by mrbogus** [comment]
For me it is the same: muting and unmuting works, but the Windows chime plays. But it seems to be a problem of Zoom, not the Streamdeck plugin, as it also appears when you use the shortcut Alt+A directly in Zoom to mute/unmute.

**Comment by vanclute** [comment]
Very interesting.  I'm not using the ctrl-A shortcut, just the mute button, but maybe behind the scenes that's all it's doing?  I'm going to explore maybe just using a keyboard shortcut rather than the "special" button and see how that goes.

**Comment by vanclute** [comment]
Oh also it appears the shortcut is Alt-A, not ctrl-A.

**Comment by vanclute** [comment]
Alt-A also produces the Windows Chime sound when the hotkey trigger button is pressed.

**Comment by vanclute** [comment]
I wish there was a solution for this as it's super annoying, and means I can't use the StreamDeck to mute/unmute myself.  I have a "Producer" role for numerous meetings each week and constantly need to mute/unmute myself, trigger sounds, etc.  Having to go to the mouse or use the mute button on my mic (which then fails to unmute PC sounds) is frustrating.

**Comment by JelleHol** [comment]
I had the same issue, but managed to solve this by marking the shortcuts that I use as "Global" in the Zoom settings (as suggested in the installation instructions). Have you tried this yet?

**Comment by vanclute** [comment]
No, there is no such "Keyboard Shortcuts" option anywhere in settings for me on Windows 10.  I looked, and looked, and hunted, and googled, but could not find anything remotely resembling said option.  Maybe that's the issue, but I don't know what to do about it.

**Comment by smitmartijn** [comment]
https://support.zoom.us/hc/en-us/articles/205683899-hot-keys-and-keyboard-for-zoom - unfold the Windows section.

**Comment by vanclute** [comment]
Oh for crying out loud... those are the ZOOM preferences???  I thought that was in Windows somewhere.  Ugh.  OK it's set now, will see if it's fixed next meeting.
