### ISSUE TITLE
Add Windows Support

### ISSUE THREAD

**Issue by oldjohngalt** [smitmartijn/streamdeck-zoom-plugin#3]
I recently made a simple Python script that detects the status of a Zoom Meeting.  https://github.com/oldjohngalt/ZoomStatus

Is there an easy way to integrate this into this plugin to make it support Windows as well?  I am not a developer and a plugin is above my head, but I might be able to help depending on what is required.

**Comment by smitmartijn** [comment]
That looks interesting for sure! The only thing I'm concerned about is the dependency on Python. Is the .exe in that repo a contained binary with Python compiled in? How did you get to that .exe?

**Comment by oldjohngalt** [comment]
Thanks!  That is correct. The exe that Icompiled has the Python interpreter built in and there are no dependencies.  

To build the exe I used pyinstaller

"pip install pyinstaller"
"pyinstaller --onefile getZoomStatus.py"

I tried to output the JSON format in the same way that your plugin did to make it easier to integrate.

**Comment by smitmartijn** [comment]
Hey @oldjohngalt - I incorporated your script into the plugin and it's available here: http://lostdomain.org/etc/com.lostdomain.zoom-v2-beta.streamDeckPlugin

If you don't mind and are able, can you test it? I don't have any native Windows systems and have been testing on a VM. Need to make sure it works. :-)

**Comment by oldjohngalt** [comment]
Wow.  I finally had the time to look through your code and you made so many improvements.  When I run the getZoomStatus.exe it is a lot faster.  

Unfortunately, when I try to run the plugin it crashes.  It looks like it might be a file system error (code 1073740791).  Is it possible there is a file on your system that wasn't included in the plugin, or a different file path?

Any ideas?  Please let met know how I can help.

`16:15:12.779                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_0b565748c80c245c6dacbb627626632b>::()::<lambda_f28c194402b52051a8ce98ebab4f5e3f>::operator ()(): Restarting plugin 'Zoom Plugin' after one minute
16:15:14.304                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_0b565748c80c245c6dacbb627626632b>::operator ()(): The plugin 'Zoom Plugin' crashed with code 1:-1073740791
16:15:14.304                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_0b565748c80c245c6dacbb627626632b>::operator ()(): Restarting plugin 'Zoom Plugin'
16:15:15.214                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_0b565748c80c245c6dacbb627626632b>::operator ()(): The plugin 'Zoom Plugin' crashed with code 1:-1073740791
`

**Comment by smitmartijn** [comment]
Yeah, I think the plugin file I linked above isn't built properly - sorry about that. 

Even though it is a lot quicker than your initial version, I'm not that happy with the speed. It takes between 2-4 seconds to run, which makes pressing the buttons slow to be effective, and the status updates lag also. I've been talking with a colleague - Joe Fitzgerald - and he offered a Go alternative that also has the UI Automation module that we're using here with Python. I need to experiment, but I'm guessing that's going to be a lot quicker.

tbc.

**Comment by oldjohngalt** [comment]
That is promising news that a Go alternative might be a lot quicker.

Would the lag be controlling the status or just to update the status?  Obviously, when you press the button you want the control to happen right away.  Looking at the code it seems that a key stroke is sent, so I assumed this was near instantaneous.

I currently use a Multi Action Switch that toggles between the two icons and sends the shortcut to mute/unmute, etc..  If I start my meeting with the icons correct, then it works great.  But it is easy to get out of sync if I start my next meeting and forget to toggle to mute before I start.  However, if the plugin synced the icons in the background and this took a few seconds I don't think the lag would be a deal breaker.  If someone used a keyboard shortcut or clicked on the Zoom meeting and the StreamDeck updated within a few seconds I think that would be fine.  Obviously a shorter lag would be better.  However, I can usually remember if I just muted/unmuted in the last 2-3 seconds.

**Comment by oldjohngalt** [comment]
I don't want to be a pest, but I was wondering if there has been any progress in the Windows version.

Is [this the Go alternative](https://github.com/hnakamur/w32uiautomation) that you were referring to?  I haven't used Go before, so I am not sure if I can be much help other than testing.  But if there is something I can do, I am happy to try.

**Comment by 2sls** [comment]
This would be an awesome plugin for Windows - i tried the 2.0 version you posted in your blog, but unfortunately I don't know why it isn't communicating with Zoom.

**Comment by Luckeyd** [comment]
Great work so far on the WIndows varient of the plugin.  I have noticed one odd behavior.  It seems this only works if Zoom is the focus window.  If you have Zoom running but another window is active, buttons such as Mute do not work.

**Comment by currentoor** [comment]
@smitmartijn would you, or anyone you know, be interested in paid work to covert this windows functionality into an NPM module.

I have an electron app that toggles zoom's mute setting. It works fine on mac via shelling out an apple script. But windows is proving difficult. I also have no windows experience.

**Comment by smitmartijn** [comment]
Closing because v2.0 has Windows support. Thanks @oldjohngalt for the first direction, eventually went with something similar, just native C++.

@currentoor - I did a quick search and Windows UI Automation doesn't seem to be a thing for node. You could create a C++ program from the code in this repo (that detects the status and triggers actions), bundle it with the module and run it via node (if that's a thing). Reach out directly if you have questions.
