### ISSUE TITLE
The process has terminated because it could not allocate additional memory

### ISSUE THREAD

**Issue by ellipticview** [smitmartijn/streamdeck-zoom-plugin#32]
After running for about a week (I set my laptop to "sleep" at night):
```
sdzoomplugin.exe  -System Error
The Process has terminated because it could not allocate additional memory.
```
Windows Task Manager shows 83% of my 16GB memory in use.

Press [OK} and the error dialogue window goes away.

Shortly after, a dialogue pops up: *Unknown Hard Error*.
![2021-03-21 12_08_35-Window](https://user-images.githubusercontent.com/8074771/115135287-c4b7bd80-a017-11eb-8817-a0f85754e789.png)

If you press [OK] it simply pops up again. There is no way to get rid of the error message.

Even after killing the process:
```
taskkill /IM sdzoomplugin.exe /F
```

The error dialogue still persists. The only way I have found to get rid of it, is to reboot my laptop.

**Comment by chaunceyc** [comment]
Same. Seems to be happening about every day lately. I sometimes have to click 30-40 times to clear the endless dialog box popups

**Comment by smitmartijn** [comment]
I'm redesigning the plugin to work with a native software client, which will work better for Windows than the current method.
