### ISSUE TITLE
Share Toggle Not Working

### ISSUE THREAD

**Issue by timjobutler** [smitmartijn/streamdeck-zoom-plugin#34]
Hi,
I am using the latest version of Zoom, Stream Deck and the Zoom plugin. Upon testing the buttons via the Stream Deck app on my tablet, all other Zoom plugin functions work except the Share Toggle. It appears to work but the Share window is not launched nor does it stop an active share.

Is it possible to confirm if this is user error or a bug?

Thanks,
Tim

**Comment by smitmartijn** [comment]
The plugin isn't tested with the Stream Deck app; it could be both.
