### ISSUE TITLE
High Sierra Permissions issue

### ISSUE THREAD

**Issue by sammybolbi** [smitmartijn/streamdeck-zoom-plugin#36]
Hello! Love the concept - however upon installation I just get the yellow triangle - I am thinking there is a disconnect between the permissions allowed by the OS - is there a way I can get an error log for you to review? THanks!

**Comment by pbyrne** [comment]
I started getting this a week ago after using things successfully for a month or so. I wonder if it's a Zoom or OS update. I checked permissions on the Stream Deck software and it's still checked for Accessibility and Automation. Other Stream Deck integrations work, but the Zoom buttons never light up like they used to and when I press them, I get a yellow triangle that briefly appears on the button.

* Zoom 5.6.7
* MacOS 11.5.2
* Stream Deck 5.0.0
* Zoom Plugin 3.0

I looked in Console in case there were warnings anything helpful, but I couldn't make heads or tails of anything I saw, nor was keyword searching for "zoom" or "stream deck" finding anything that appeared to be related. Been a few weeks now and I hadn't realized how dependent I'd become on being able to mute or leave a meeting from anywhere with the Stream Deck hardware keys. 😭 

Anything I can offer to help debug, I'm happy to do so.

**Comment by pbyrne** [comment]
I wondered if there was any significance to the fact that on my machine, the menus are title cased ("Mute Audio") vs the sentence casing I was seeing in the global definitions: https://github.com/smitmartijn/streamdeck-zoom-plugin/blob/33892febdc188b2124b2a32c55b84ba3d2b5c949/Sources/ZoomStreamDeckPlugin.cpp#L25

So I took the relevant AppleScript from https://github.com/smitmartijn/streamdeck-zoom-plugin/blob/33892febdc188b2124b2a32c55b84ba3d2b5c949/Sources/MacOS.cpp#L170-L184 and ran it through Keyboard Maestro and it successfully muted with both "Mute audio" and "Mute Audio" strings. Which is nice and suggests that's not the problem at least.

![CleanShot 2021-08-30 at 12 21 38@2x](https://user-images.githubusercontent.com/34053/131379036-1885c959-08ca-42ba-9fd2-c958a1f15ed6.png)

**Comment by smitmartijn** [comment]
macOS can reset permissions after/during an update sometimes. Even though an app has the checkbox checked in the accessibility settings, sometimes you need to uncheck it, restart the app, and recheck it.
