### ISSUE TITLE
Win10: Status not updating

### ISSUE THREAD

**Issue by Raiden38** [smitmartijn/streamdeck-zoom-plugin#37]
The plugin works perfecly when you press on the buttons however the status does not update (Always return tu gray/white icon regardless of the status). I am on win10, and the zoom language is set as English. I am using the latest version of Zoom, Streamdeck and Plugin. Any ideas?

**Comment by smitmartijn** [comment]
I'm redesigning the plugin to work with a native software client, which will work better for Windows than the current method.

**Comment by fussel132** [comment]
Hey just wanted to ask if there is any progress regarding that topic? Also using latest Streamdeck / Plugin Version and Windows 11 (Zoom in English) and status is not updating as well. Toggling the mic or camera works however there is always the grey icon. That does not count for the "Leave Meeting" button which is only grey in case you are not in a meeting. Looking forward to an update :))
