### ISSUE TITLE
Actions not working when fullscreen on macos

### ISSUE THREAD

**Issue by junior-n30** [smitmartijn/streamdeck-zoom-plugin#38]
I'm using the plugin with my MacBook Pro and an external monitor. My zoom is usually on this second screen and whenever my MacBook's screen is on a fullscreen application, then the buttons to toggle mute, camera, etc. don't work.

After a bit of testing, I found that it's the `click` action in the apple script that aren't executing in those cases. Using the shortcut instead seems to work.

For instance, in a custom script, I replaced the line that ends up being 
```
click (menu item "UnMute audio" of menu 1 of menu bar item "Meeting" of menu bar 1)
```
By 
```
keystroke "A" using {shift down, command down}
```
And it works with the fullscreen.

**Comment by smitmartijn** [comment]
Thanks. That kind of makes sense; the applescript looks at the current desktop. macOS hides the menu when you go full screen, so the plugin won't be able to find it. 

The work around with the shortcut will only work when you've got Zoom in focus, so it only solves when you use Zoom always in fullscreen or in focus. My advice is to not use the native fullscreen, just resize the window so it takes up all the screen real-estate.
