### ISSUE TITLE
action to trigger custom menus based on text similar to the custom shortcut action?

### ISSUE THREAD

**Issue by markusd1984** [smitmartijn/streamdeck-zoom-plugin#40]
I love this plugin, thanks for sharing the hard work! I was wondering given some features could potentially be added as action buttons i.e. for interactive meetings where reactions are used an instructor needs to [clear the feedback ](https://github.com/smitmartijn/streamdeck-zoom-plugin/issues/39)quite regularly.

Could we have a custom menu trigger where we just enter the text of the menu item so it can be triggered?

This would be amazing as more triggers could be setup according to preference and even when new ones would become available in the zoom app or if the wording were to change.

**Comment by smitmartijn** [comment]
I'm redesigning the plugin to work with a native software client and I'll take custom actions into consideration there.

In the mean time, this could be done using the method keyboard Maestro: https://lostdomain.org/2020/03/13/a-better-zoom-experience-with-a-stream-deck/
