### ISSUE TITLE
Unknown hardware error won't dissapear

### ISSUE THREAD

**Issue by RobertGemmaJr** [smitmartijn/streamdeck-zoom-plugin#41]
Plugin crashes every so often and system error will not disappear. Whenever I hit "OK" or close the popup it immediately appears again. The popup forces itself to always be on top as well so there's no way for me to hide it

![image](https://user-images.githubusercontent.com/38439940/140383253-9ed8e15c-a3b8-49ff-a902-ae1ef4845360.png)

**Comment by smitmartijn** [comment]
I'm redesigning the plugin to work with a native software client, which will work better for Windows than the current method.
