### ISSUE TITLE
Feature Request: More Actions

### ISSUE THREAD

**Issue by weirded** [smitmartijn/streamdeck-zoom-plugin#5]
Thank you for this plugin, I use it all-day, every day, and have recommended it to several coworkers! 

I would love to see further actions added (I currently solve these using Keyboard Maestro, but it isn't very reliable/fast): 
- Toggle Speaker/Gallery View
- Reactions (👍🏻/👏)
- Launch next Zoom meeting (based on Meetings tab) 

My Mac dev skills are non-existent unfortunately, otherwise I'd submit a PR myself.

**Comment by statik** [comment]
@smitmartijn do you have any tips for testing the embedded applescript? I started working on a PR to add the toggle speaker/gallery view, but got stuck trying to test out the changes to the applescript.

**Comment by smitmartijn** [comment]
@statik Use the Script Editor that's on your macOS. The only cumbersome part is to remove the backslashes and "\n" from the script in the source, and then putting those back when putting the script back into the code.

If anyone wants to pick up these extra actions; go ahead! I'm focusing on Windows support first.

**Comment by smitmartijn** [comment]
This is now possible in v3.0 (soon to be in the StreamDeck Store) by adding a custom shortcut button and configuring it to run the shortcut you need. Please update to v3.0 (when it's available, usually only takes a day or so for them to publish it) and try it. Re-open issue if it's not working.
