### ISSUE TITLE
Not Working in High Sierra

### ISSUE THREAD

**Issue by vitzter** [smitmartijn/streamdeck-zoom-plugin#6]
The plug in does not seem to work in High Sierra even after enabling Stream Desk in Privacy/Accessibility.

**Comment by smitmartijn** [comment]
I'm going to need a little more, it works fine when I just tested it on 10.13. What happens when you press a button? Can you get the logs that StreamDeck generates? https://developer.elgato.com/documentation/stream-deck/sdk/create-your-own-plugin/ (bottom)

**Comment by smitmartijn** [comment]
Closing due to lack of information.
